
logging:
  level:
    org:
      springframework:
        web: DEBUG
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql.cqvbxvnhcvmw.ap-south-1.rds.amazonaws.com/springbootdb?allowPublicKeyRetrieval=true&useSSL=false
    username: admin
    password: purna21619
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

