name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
   # - name: Build the Docker image
  #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: docker push
      run: |
        # docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 972440106609.dkr.ecr.ap-south-1.amazonaws.com
        # docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/java_demo_gitactions
          docker build -t nodejsapplication .
         # docker push ${{secrets.DOCKER_USER}}/java_demo_gitactions
          docker tag nodejsapplication:latest 972440106609.dkr.ecr.ap-south-1.amazonaws.com/nodejsapplication:latest
          docker push 972440106609.dkr.ecr.ap-south-1.amazonaws.com/nodejsapplication:latest
